import os.path as path
from typing import Literal

class BIDSPaths:
    def __init__(self, root, subject: str, session: int, run: int):
        self.root = root
        self.subject = subject
        self.ses = f'{session:02d}'
        self.run = f'{run:02d}'

    def sourcedata(self):
        return path.join(self.root, 'sourcedata')

    def derivatives(self):
        return path.join(self.root, 'derivatives')

    def session(self):
        return path.join(self.root, f'sub-{self.subject}', f'ses-{self.ses}')

    def anatomical_surface(self, hemisphere: Literal['L', 'R']):
        return path.join(
            self.session(),
            'anat',
            f'sub-{self.subject}_ses-{self.ses}_acq-MEMPRvNav_rec-RMS_hemi-{hemisphere}_midthickness.surf.gii',
        )

    def functional_surface(self, hemisphere: Literal['L', 'R']):
        return path.join(
            self.session(),
            'func',
            f'sub-{self.subject}_ses-{self.ses}_task-langLocal_run-{self.run}_hemi-{hemisphere}_space-fsaverage_bold.func.gii'
        )

    def functional_volume(self):
        return path.join(
            self.session(),
            'func',
            f'sub-{self.subject}_ses-{self.ses}_task-langLocal_run-{self.run}_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz'
        )

    def derivatives_fsl(self):
        return path.join(self.derivatives(), 'fsl', f'sub-{self.subject}', f'ses-{self.ses}')

    def derivatives_fsl_design(self):
        '''Directory for the files required by FSL to run analysis from a design.'''
        return path.join(self.derivatives_fsl(), 'design')

    def prepared_firstlevel_design_file(self, extension='.fsf'):
        '''Path to the FSF design file.
           extension - Desired file extension, with preceding dot. For no extension, use an empty string.
        '''
        return path.join(
            self.derivatives_fsl_design(),
            f'sub-{self.subject}_ses-{self.ses}_task-langLocal_run-{self.run}_desc-design_firstlevel{extension}'
        )

    def confounds_fmriprep(self):
        return path.join(
            self.session(),
            'func',
            f'sub-{self.subject}_ses-{self.ses}_task-langLocal_run-{self.run}_desc-confounds_timeseries.tsv'
        )

    def confounds_fsl(self):
        return path.join(
            self.derivatives_fsl_design(),
            f'sub-{self.subject}_ses-{self.ses}_task-langLocal_run-{self.run}_desc-confounds_fsl.txt'
        )

    def stats_surface_fsl(self):
        '''Directory for stats files generated by a surface-based analysis'''
        return path.join(self.derivatives_fsl(), 'stats-surf')
    
    def stats_volume_fsl(self):
        '''Directory for stats files generated by a volume-based analysis'''
        return path.join(self.derivatives_fsl(), 'stats-volume')
