"""
Perform surface-based first level analysis.

The following executables should be available in your PATH:
- `wb_command` from Connectome Workbench
- `feat_model` from FSL
- `film_gls` from FSL
"""

import subprocess
from typing import Optional

from bids_path_utils import BIDSPaths

from fsl.data import featanalysis
import os
import os.path as path
import datetime
import pandas as pd

import logging
logger = logging.getLogger(__name__)

def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

def get_number_of_volumes(input_4d_data_path: str):
    '''Use Connectome Workbench to determine the number of volumes/maps in 4d input data'''
    logger.info(f'Getting number of volumes in {input_4d_data_path}')
    response = subprocess.run([
        'wb_command',
        '-file-information',
        '-only-number-of-maps',
        input_4d_data_path
    ], capture_output=True)
    response.check_returncode()

    volumes = response.stdout.decode('ascii').strip()
    return int(volumes)

def generate_design_matrix_files(fsf_path: str):
    '''Generate the design matrix files from the FSF'''
    logger.info(f'Generating design matrix files from {fsf_path}')
    response = subprocess.run([
        'feat_model',
        fsf_path.removesuffix('.fsf')
    ])
    response.check_returncode()
    

def prepare_fsl_confound_file(
    confounds_tsv_path: str, # Path to confounds TSV generated by fMRIPrep
    confound_ev_cols: list[str], # Confound EV columns to use
    output_confounds_path: str, # Path to output confounds file
    demean: bool = True # Whether to subtract the mean from each confound variable
):
    confounds_tsv = pd.read_csv(confounds_tsv_path, sep='\t')
    confounds_tsv = confounds_tsv[confound_ev_cols]

    if demean:
        confounds_tsv = confounds_tsv - confounds_tsv.mean()

    confounds_tsv = confounds_tsv.fillna(0)

    confounds_tsv.to_csv(
        output_confounds_path,
        sep='\t',
        index=False,
        header=False,
    )

def prepare_design(
    template_fsf_path: str, # Input template design
    prepared_fsf_path: str, # Output prepared design
    functional_volume_4d_path: str, # 4d brain data to run FEAT on
    firstlevel_outputs_path: str, # Directory where FEAT will dump analysis files to
    ev_paths: list[str], # EV/timing file in 3 column format
    confounds_path: Optional[str] = None, # Confounds file for FSL
    tr: float = 2,
    hpf: float = 128,
):
    '''Modify the template design FSF to be used with the given functional MRI
    data, and save the modified design to the output path.'''
    logger.info('Preparing design')
    design = featanalysis.loadFsf(template_fsf_path)

    design['outputdir'] = firstlevel_outputs_path
    design['npts'] = get_number_of_volumes(functional_volume_4d_path)
    design['tr'] = tr
    design['paradigm_hp'] = hpf
    design['inputtype'] = 2
    design['featwatcher_yn'] = 0 # don't want to open the web browser
    if confounds_path:
        design['confoundevs'] = 1

    # regular EVs
    for ev_number, ev_path in enumerate(ev_paths, 1):
        if f'custom{ev_number}' not in design:
            raise ValueError('Too many explanatory variables (EVs) passed in for the given design template! If you need to add more EVs, you should load your design in FEAT and add all your variables first, then re-save the template.')
        
        evtitle = design[f'evtitle{ev_number}']
        logger.info(f'EV {evtitle}: using file {ev_path}')
        design[f'custom{ev_number}'] = ev_path

    logger.info('Writing design file')
    with open(prepared_fsf_path, 'w') as out_fsf:
        out_fsf.write(f'# This design was automatically generated from {template_fsf_path} using firstlevel.py\n\n')

        if 'feat_files' in design:
            del design['feat_files']
        out_fsf.write(f'set feat_files(1) "{functional_volume_4d_path.removesuffix('.nii.gz')}"\n')

        if 'confoundev_files' in design:
            del design['confoundev_files']
        if confounds_path:
            out_fsf.write(f'set confoundev_files(1) "{confounds_path}"\n')

        for setting, value in design.items():
            if not is_number(value):
                out_fsf.write(f'set fmri({setting}) "{value}"\n')  
            else:
                out_fsf.write(f'set fmri({setting}) {value}\n')  

def analyze_surface(
    anatomical_surface_path: str,
    functional_surface_4d_path: str,
    design_matrix_path: str, # .mat file generated from the FSF design by FSL's feat_model
    contrast_path: str, # .con file generated from the FSF design by FSL's feat_model
    stats_output_path: str # Directory to put stats files
):
    logger.info('Analyzing surface with film_gls')
    response = subprocess.run([
        'film_gls',
        '--mode=surface',
        f'--rn={stats_output_path}',
        f'--in={functional_surface_4d_path}',
        f'--in2={anatomical_surface_path}',
        f'--pd={design_matrix_path}',
        f'--con={contrast_path}',
        # '--sa', '--ms=15', '--epith=5' # for full prewhitening TODO: why does this crash film_gls?
    ])
    response.check_returncode()

if __name__ == "__main__":
    logging.basicConfig(filename='logs/firstlevel.log', level=logging.INFO)
    logger.info(f'=== Started firstlevel.py at {datetime.datetime.now()} ===')

    bids = BIDSPaths(root='/workdir/deafmeg/', subject='DMEGp01', session=1, run=1)
    hemisphere = 'L'
    template_fsf = '/workdir/deafmeg/sourcedata/firstlevel_4cond.fsf'
    os.makedirs(bids.derivatives_fsl_design(), exist_ok=True)

    prepare_fsl_confound_file(
        confounds_tsv_path=bids.confounds_fmriprep(),
        confound_ev_cols=['rmsd', 'white_matter'],
        output_confounds_path=bids.confounds_fsl(),
        demean=True
    )

    prepare_design(
        template_fsf_path=template_fsf,
        prepared_fsf_path=bids.prepared_firstlevel_design_file(),
        functional_volume_4d_path=bids.functional_volume(),
        ev_paths=[
            path.join(bids.derivatives(), 'timing/sub-DMEGp01/ses-01/sub-DMEGp01_ses-01_run-01_desc-timingAction.txt'),
            path.join(bids.derivatives(), 'timing/sub-DMEGp01/ses-01/sub-DMEGp01_ses-01_run-01_desc-timingASL.txt'),
            path.join(bids.derivatives(), 'timing/sub-DMEGp01/ses-01/sub-DMEGp01_ses-01_run-01_desc-timingControl.txt'),
            path.join(bids.derivatives(), 'timing/sub-DMEGp01/ses-01/sub-DMEGp01_ses-01_run-01_desc-timingSilly.txt'),
        ],
        confounds_path=bids.confounds_fsl(),
        firstlevel_outputs_path=bids.stats_volume_fsl()
    )

    generate_design_matrix_files(bids.prepared_firstlevel_design_file())

    analyze_surface(
        anatomical_surface_path=bids.anatomical_surface(hemisphere),
        functional_surface_4d_path=bids.functional_surface(hemisphere),
        design_matrix_path=bids.prepared_firstlevel_design_file('.mat'),
        contrast_path=bids.prepared_firstlevel_design_file('.con'),
        stats_output_path=bids.stats_surface_fsl()
    )